name: tests
# Note: name shows up in a badge. Be careful about renaming.

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    # TODO: run on more target OSes
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      # Java 11 needed for resolving the Android Gradle Plugin
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache Kotlin Native compiler
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: kotlin-native-compiler-${{ runner.OS }}

      - name: Test with Gradle
        run: ./gradlew allTests --no-daemon
