name: Publish to Maven

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Maven Registry'
        required: true
        default: 'GCloud'
        type: choice
        options:
          - GCloud
          - Sonatype
          - Both

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Add secret Gradle properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.VARABYTE_GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

      - name: Cache Kotlin Native compiler
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: kotlin-native-compiler-${{ runner.OS }}

      # TODO: Add Sonatype

      - name: Publish JVM/JS (GCloud)
        if: matrix.os == 'ubuntu-latest' # Doesn't have to be Linux but it tends to be the fastest image
        run: |
          ./gradlew publishJvmPublicationToGCloudMavenRepository --no-daemon
          ./gradlew publishJsPublicationToGCloudMavenRepository --no-daemon

      - name: Publish Linux (GCloud)
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew publishLinuxX64PublicationToGCloudMavenRepository --no-daemon

      - name: Publish Mac (GCloud)
        if: matrix.os == 'macos-latest'
        run: |
          ./gradlew publishMacosX64PublicationToGCloudMavenRepository --no-daemon
          ./gradlew publishMacosArm64PublicationToGCloudMavenRepository --no-daemon

      - name: Publish Win (GCloud)
        if: matrix.os == 'windows-latest'
        run: ./gradlew publishMingw64PublicationToGCloudMavenRepository --no-daemon
